name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu:22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.mglue }} -p ${{ secrets.dckr_pat_uMEJDaFijR24OzXMdTcFqBwELk4 }}
    
    - name: Build the Docker image
      run: docker build -t telegram-crawler-app:v-2.1 -f Dockerfile.app .

    - name: Tag the Docker image
      run: docker tag telegram-crawler-app:v-2.1 mglue/telegram-crawler-app:v-2.1

    - name: Push to Docker Hub
      run: docker push mglue/telegram-crawler-app:v-2.1
